version: "3.9"
services:
  
  ctf:
    build: 
     context: .
     dockerfile: Dockerfile

    volumes:
      - ../:/home/work

    env_file:
      - env


    restart: always
    container_name: ctf
    runtime: nvidia

#    ports:
#      - 8000:8888
#    command: poetry run jupyter-lab --no-browser --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.notebook_dir='/home/work'
    command: sleep 4000000000

    




